Maksym Severyn : zmiana plikow do json jjdzr4 ib 17
infoshareacademy/jjdzr4-i-ll-be-back pull request #16
Opened 2021-11-15 15:50 UTC by maksym-severyn

Przerobiłem zapisywanie/odczyt z obecnych .csv do modnych json-ów :)
Namęczyłem się w holerę, bo standardowo nie chciał zapisywać pola z datą, bo miała tym LocalDateTime, ani przez Jacksona, ani przez Gsona. Na szęście znalazłem rozwiązanie - 2x klasy w folderze Gson - proszę nie pytać jak to działa - nie wiem :)

2021-11-15 22:58 UTC, Pieczarone commented
Ogólnie przejrzałem wygląda to dobrze, za bardzo dzisiaj nie mam czasu żeby pobrać kod i otestować niestety. (Wróciłem po 22 z pracy). Postaram się jutro pobrać kod i bardziej szczegółowo go obejrzeć

2021-11-16 16:49 UTC, OskarBemka requested changes

2021-11-16 16:49 UTC, OskarBemka commented on WorkAndFun/src/main/java/pl/infoshare/FileActions.java
> +    public static ArrayList<Announcement> loadAnnouncementsFromFile(Path path) {
ja bym tylko zmienil nazwe tej metody na readAnnouncementsFromFile, bo skoro wyzej mamy metode writeAnnoun... to analogicznie tutaj powinno byc read.

2021-11-17 12:29 UTC, maksym-severyn commented
@OskarBemka poprawiłem nazwę metody

2021-11-17 14:10 UTC, OskarBemka approved these changes

2021-11-19 12:06 UTC, merged