Menu added
infoshareacademy/jjdzr4-i-ll-be-back pull request #2
Opened 2021-09-28 06:15 UTC by OskarBemka

2021-09-28 08:12 UTC, BienkowskiTomasz requested changes
Menu:24-26 String jako typ danych do switcha jest w tym przypadku zbyt rozbudowanym typem, optymalniejszy pod względem wydajności byłby prymitywny typ danych np. int.

Menu:24 "String string = scanner.nextLine();" - mało mówiąca nazwa zmiennej, userInput lub coś różniącego od string byłoby lepsze.

Menu:45-47 - case 7 - brak instrukcji przerwania break; lub System.exit(0);.

2021-09-28 08:35 UTC, OskarBemka commented
Menu:24-26 użyłem Stringa z dwóch powodów, metoda bardziej elastyczna na przyszłość , gdybyśmy chcieli pobierać coś innego niż liczby z klawiatury oraz dzięki temu nie musiałem pisać wyjątku.

Menu:24 "String string = scanner.nextLine();" - zmienna ta nie wychodzi poza metodę , także jej nazewnictwo nie jest specjalnie ważne moim zdaniem, ale jeśli się mylę to mnie poprawcie.

Menu:45-47 - dzięki za uwagę, poprawię to jak reszta się wypowie

2021-09-28 15:05 UTC, mariuszszymanskipl commented
Pamiętajcie, że możecie dodawać swoje komentarze bezpośrednio przy kodzie 😉 
Wystarczy kliknąć ➕ przy danej linii:
<img width="853" alt="Screenshot 2021-09-28 at 17 03 09" src="https://user-images.githubusercontent.com/25279453/135114026-c34e6d6e-0626-422b-8d9c-a66387feca08.png">

2021-09-28 19:45 UTC, maksym-severyn commented on WorkAndFun/src/main/java/pl/infoshare/Menu.java
> +        String string = scanner.nextLine();
Ja bym nie nazywał zmiennej "string". Może ta zmienna nigdzie węcej nie będzie używana, ale to po prostu nie jest zgodne z zasadami clean code, a proponuję żebyśmy pisali zawsze jak najlepiej się da i przyzwyczajać się do tego.

2021-09-28 19:46 UTC, maksym-severyn commented on WorkAndFun/src/main/java/pl/infoshare/Menu.java
> +                System.out.println("Ej Ty! Ogarnij sie i wprowadz poprawny parametr !");
brakuje tu "break"

2021-09-28 19:48 UTC, maksym-severyn requested changes
Prośba o drobne poprawki, zgodnie z komentarzami ;)

2021-09-29 15:50 UTC, BienkowskiTomasz commented on WorkAndFun/src/main/java/pl/infoshare/Menu.java
> +        } catch (Exception ignored) {
Jeśli dobrze pamiętam z warsztatów, to dobrze wskazać dokładny wyjątek, a nie grupę Exception, czyli tu by było InputMismatchException. Ale mogę się mylić. ;-)

2021-09-29 18:40 UTC, Pieczarone approved these changes
LGTM

2021-10-01 19:45 UTC, maksym-severyn reviewed
Pytanie do @mariuszszymanskipl w komentarzu

2021-10-02 22:17 UTC, mariuszszymanskipl commented on WorkAndFun/src/main/java/pl/infoshare/Menu.java
> +        } catch (Exception ignored) {
@maksym-severyn Tak, wyjątki trzeba zawsze obsługiwać (lub przekazywać obsługę 'wyżej'). 
W metodzie `getUserInput` mamy wywołanie metody `scanner.nextByte()` które może rzucić jeden z wyjątków (InputMismatchException, NoSuchElementException, IllegalStateException). Wszystkie są wyjątkami typu RuntimeException, więc nie ma obowiązku opakowywania kodu w blok try-catch, ale jeśli jakiś poleci (np. wpiszemy literę zamiast cyfrę), to cała aplikacja się 'wysypie' 😉 I nic nam nie pomoże default case w switch-case 😉 
Ja bym więc zostawił tutaj blok try-catch żeby obsłużyć sytuację, gdyby _nextByte()_ rzuciło wyjątek. I zostawiłbym łapanie wszystkich Exceptions, żeby nie wypisywać każdego z osobna.
Obsłużenie wyjątku może również polegać na zwróceniu jakiejś konkretnej liczby, tak jak to zostało zrobione tutaj (niejawnie 😉 ). Tylko ja bym dla czytelności zrobił to tak:
```
private byte getUserInput() {
  try {
      return new Scanner(System.in).nextByte();
  } catch (Exception e) {
      return -1;
  }
}
```
I już jest exception obsłużony 😜

2021-10-02 22:17 UTC, mariuszszymanskipl commented on WorkAndFun/src/main/java/pl/infoshare/Menu.java
> +        System.out.println("7 - Zakoncz program");
```suggestion
        System.out.println("0 - Zakoncz program");
```
tak na wszelki wypadek, gdyby doszła opcja 7, 8 itd.

2021-10-04 10:40 UTC, maksym-severyn reviewed
Rozwiązałem konflikt w klasie Main

2021-10-06 17:37 UTC, maksym-severyn approved these changes
LGTM

2021-10-06 17:39 UTC, merged