Completed task JJDZR4IB-22
infoshareacademy/jjdzr4-i-ll-be-back pull request #23
Opened 2021-12-19 22:16 UTC by Pieczarone

Póki co bez frontu, wszystko działa z walidacją (dodałem dwa ogłoszenia do db nie wiem dlaczego nie mogłem ich usunąć przez delete/id)

2021-12-19 22:19 UTC, Pieczarone commented
Zapomniałem dodać, póki co bez polskich znaków bo chciałem jak najszybciej to wrzucić, a nie chciałem tracić czasu na to

2021-12-20 11:06 UTC, OskarBemka requested changes

2021-12-20 11:06 UTC, OskarBemka commented on WorkAndFun/src/main/java/pl/infoshare/workandfun/announcements/announcement_repo/entity/Announcement.java
>      private ServiceType serviceType;
Trzeba by się pochylić nad wyborem serviceType, ponieważ aktualnie wybór jest na zasadzie wszystko w jednym, a powinno być na zasadzie drzewa. Wiem, że nie było nic takiego na zajęciach, jednak fajnie by było to ogarnąć. Można napisać do jakiegos trenera z prośbą o wsparcie. Nie czepiam się tego, jedynie zostawiam moją sugestię i proponuje o dopisanie TODO

2021-12-20 19:26 UTC, Pieczarone commented on WorkAndFun/src/main/java/pl/infoshare/workandfun/announcements/announcement_repo/entity/Announcement.java
>      private String price;
Tak, zostawiłem to świadomie by trzeba było przerobić te pole prawdopodobnie

2021-12-21 11:26 UTC, OskarBemka requested changes

2021-12-21 11:26 UTC, OskarBemka commented on WorkAndFun/src/main/java/pl/infoshare/workandfun/announcements/announcement_repo/entity/additionals/Type.java
> +    SERVICE_OFFER("Oferuje usługę"),
oferujĘ

2021-12-25 11:57 UTC, maksym-severyn requested changes
Na razie jeden komentarz, ale bardziej globalny, co do podejścia do dodania ogłoszenia.
Jeszcze ogarniam Thymeleaf także być moe coś jeszcze dopiszę do samych formularzy, po przerobieniu tematu

2021-12-25 12:42 UTC, Pieczarone commented on WorkAndFun/src/main/java/pl/infoshare/workandfun/announcements/announcement_repo/entity/Announcement.java
> +    @Size(min = 10,max = 60)
Czyli w dużym skrócie jak dobrze rozumiem. W osobnej klasie trzeba stworzyć konstruktor Do ogłoszeń i w nim mapowanie do entity?

2021-12-25 15:10 UTC, maksym-severyn commented on WorkAndFun/src/main/java/pl/infoshare/workandfun/announcements/announcement_repo/entity/Announcement.java
> +    @Size(min = 10,max = 60)
@Pieczarone 
Czyli w osobnej klasie coś typu AnnouncementAddDto, gdzie to jest jeden do jednego co w Announcement, z wyłączeniem pola ID, które w Announcement jest autoincrementowane.
Przy czym w Announcement trzeba usunąć wszystko co jest związane z jakąkolwiek logiką, czyli na przykłąd walidację, i przenieść te rzeczy do AnnouncementAddDto. W Encji ma zostać tylko wpis do autoincrementacji.
Następnie w pakiecie Config tworzysz mapper, który będzie mapował z Announcement do AnnouncementAddDto i na odwrót (2x metody). Dalej do klasy Service wstrzykujesz nasze Repo oraz Mapper. Następnie, przerabiasz w serwisie metodę np. "create". Ona ma dostawać jako parametr ten AnnouncementDto, następnie za pomocą mappera go mapować do już finalnego Announcement, i wtedy wrzucać Announcement do bazy.

Przy takim podejściu jest bardzo fajne zabezpieczenie naszego Announcement od tego, co do niego przychodzi z zewnątrz, z endpointów. Nie ma opcji, że coś zbędnego nadpiszemy, czy prześlemy do bazy, (zwłaszcza przy na przykład edycji) lub odwrotnie - wyślemy na endpoint, bo GET-y powinne działać tak samo - pobierać np Announcement, mapować go do Dto (który nie ma powiedzmy pól z jakimiś wrażliwymi danymi) i dopiero ten Dto wystawiać na serwer.

2021-12-30 11:47 UTC, OskarBemka approved these changes

2021-12-30 12:33 UTC, merged