Completed frontend
infoshareacademy/jjdzr4-i-ll-be-back pull request #27
Opened 2022-01-22 19:22 UTC by Pieczarone

2022-01-28 14:34 UTC, BienkowskiTomasz approved these changes
Kilku rzeczy się czepiłem, ale generalnie działa git, więc moim zdaniem można mergować, a poprawki nanieść w nieokreślonej przyszłości. ;-)

2022-01-29 21:14 UTC, maksym-severyn requested changes
Nie działa walidacja!

2022-01-29 21:14 UTC, maksym-severyn commented on WorkAndFun/src/main/java/pl/infoshare/workandfun/announcements/dto/AddAndEditAnnouncementDto.java
> +    @NotBlank(message = "Nie może być odstępem")
potwierdzam, lepiej coś typu "nie uzywaj białych znaków", lub to co Tomek zasugerował

2022-01-29 21:14 UTC, maksym-severyn commented on WorkAndFun/src/main/java/pl/infoshare/workandfun/announcements/dto/AddAndEditAnnouncementDto.java
> +>>>>>>> origin/master
tu jakieś linijki zbędne zostały, przy mergowaniu

2022-01-29 22:07 UTC, maksym-severyn approved these changes

2022-01-29 22:08 UTC, merged