Testy
infoshareacademy/jjdzr4-i-ll-be-back pull request #29
Opened 2022-01-23 13:32 UTC by OskarBemka

2022-01-25 13:40 UTC, maksym-severyn requested changes
Troszkę naskrobałem komentarzy :)

2022-01-25 13:40 UTC, maksym-severyn commented on WorkAndFun/src/test/java/pl/infoshare/workandfun/announcements/AnnouncementServiceTest.java
> +        Assertions.assertThrows(AnnouncementNotFoundException.class, () -> announcementService.findById(id));
```suggestion
        Assertions.assertThrows(AnnouncementNotFoundException.class, () -> announcementService.findByIdConvertToDto(id));
```
Jest błąd, bo testujesz inną metodę klasy AnnouncementService. Samo findById() zostało przetestowane wcześniej.
Poza tym proponuję bazować się na moich sugestiach, co pisałem wcześniej, przy sprawdzeniu wyjątku od findById()

2022-01-25 13:40 UTC, maksym-severyn commented on WorkAndFun/src/test/java/pl/infoshare/workandfun/announcements/AnnouncementServiceTest.java
> +    void shouldDeleteAnnouncementByIdIfExist() {
można jeszcze dodać metodę sprawdzająca czy rzuci wyjatkiem jak nie znajdzie, analogicznie jak poprzednio. Mogę to sam dodać, jesli chcesz, jak będę dopisywał swoje parę testów

2022-01-27 18:36 UTC, OskarBemka commented on WorkAndFun/src/test/java/pl/infoshare/workandfun/announcements/AnnouncementServiceTest.java
> +        Assertions.assertThrows(AnnouncementNotFoundException.class, () -> announcementService.findById(id3));
co na celu ma sprawdzenie "isInstanceOf(RuntimeException.class)" skoro mnie interesuje AnnouncementNotFoundException.class, który dziedziczy po RuntimeException ?

2022-01-27 18:37 UTC, OskarBemka commented on WorkAndFun/src/test/java/pl/infoshare/workandfun/announcements/AnnouncementServiceTest.java
> +    void shouldFindByIdAndMapToDto() {
zmiana kodu produkcyjnego na potrzeby testów ?

2022-01-27 18:39 UTC, maksym-severyn commented on WorkAndFun/src/test/java/pl/infoshare/workandfun/announcements/AnnouncementServiceTest.java
> +        Assertions.assertThrows(AnnouncementNotFoundException.class, () -> announcementService.findById(id3));
Tutaj się zgadzam - linijka o RuntimeException chyba zbędna - rozpędziłem się :) Ale message o hasNoCause bym zostawił

2022-01-27 18:47 UTC, maksym-severyn commented on WorkAndFun/src/test/java/pl/infoshare/workandfun/announcements/AnnouncementServiceTest.java
> +    void shouldFindByIdAndMapToDto() {
Pamiętajmy że 
1) Normalnie testy piszą się równolegle z implementacją. 
2) Jak mówił Marek - jak coś nie da się prosto i łatwo przetestować, to raczej świadczy o tym że gdzieś implementacja nie jest czysto napisana, a więc test może świadczyć o tym że coś może być poprawione/zmodyfikowane w implementacji.
3) TDD opiera się na tym, że piszesz implementacje pod testy.
Podsumowując - uważam że lekkie modyfikację na zasadzie dodania equals i hashcode (które niemal są boilerplate) w celu ułatwienia i co ważne - znaczącego podwyższenia jakości przeprowadzanych testów, jest dopuszczalne. 
Dobrym przykładem jest to, że zapomniałeś w jednym z testów przetestować jednego pola klasy announcement (nameOfAdviser). Świadczy to o tym, że:
1. Łatwo zapomnieć o polu
2. Jak dojdzie nowe pole, to na 90% zostanie zapomniane o tym żeby zmodyfikować test, bo on zaświeci się na zielono.
Equals i hashcode rozwiązują te problemy

2022-01-27 23:38 UTC, maksym-severyn approved these changes
LGTM

2022-01-27 23:39 UTC, merged